<?php


namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Variables extends Model
{
    public static $array = [
        "LogIn" =>[
            "SIGN_IN" =>"Sign In",
            "ALREADY_HAVE_ACCOUNT" =>"Already have an account?  Welcome back!",
            "EMAIL_LABEL" =>"Email Address*",
            "PASSWORD_LABEL" =>"Password*",
            "FORGOT_PASSWORD" =>"Forgot Password?",
            "LOGIN_WITH" =>"Or Log In with",
            "ONE_TIME_PASSWORD" =>"One Time Password (OTP)",
            "LOGIN" =>"Log In",
            "NEW_TO_FANCLUB" =>"New to Fanclub?",
            "CREATE_ACCOUNT" =>"Create Account",
            "SKIP" =>"Skip",
            "PASSWORD" =>"Password",
            "REQUEST_OTP" =>"Request OTP",
        ],
        "VerifyOtp" =>[
            "OTP_VERIFICATION" =>"OTP Verification",
            "SENT_OTP_MSG" =>"We have sent the OTP to your email address",
            "RESEND_OTP" =>"Resend OTP",
            "SUBMIT" =>"Submit",
        ],
        "ForgotPassword" =>[
            "FORGOT_PASSWORD" =>"Forget your Password",
            "DESC" =>"Keep calm, we’ve got you covered.  Just enter your email address below to reset your password",
            "EMAILADDRESS_LABEL" =>"Email Address*",
            "STILL_NEED_HELP" =>"Still Need Help?",
            "SUBMIT" =>"Submit",
        ],
        "ResetPassword" =>[
            "RESET_PASSWORD" =>"Reset Password",
            "ENTER_NEW_PASSWORD_MSG" =>"Please enter a new password",
            "NEW_PASSWORD_LABEL" =>"New Password*",
            "CONFIRM_PASSWORD_LABEL" =>"Confirm Password*",
            "RESET" =>"Reset",
        ],
        "CreateAccount" =>[
            "CREATE_ACCOUNT" =>"Create Account",
            "DESC" =>"Join our community of music fans now and start to build your Fanclub collection",
            "REGSITER_AS_LABEL" =>"Register as*",
            "EMAIL_ADDRESS_LABEL" =>"Email Address*",
            "PHONE_NUMBER_LABEL" =>"Phone Number",
            "YOUR_NAME_LABEL" =>"Your Name*",
            "BAND_OR_SOLO_ARTIST" =>"Are you a band or solo artist?",
            "BAND_LABEL" =>"Band",
            "SOLO_ARTIST_LABEL" =>"Solo Artist",
            "BAND_OR_ARTIST_NAME" =>"Band or Artist Name*",
            "CONTACT_NAME_LABEL" =>"Contact Name*",
            "CONTACT_EMAIL_ADDRESS_LABEL" =>"Contact Name*",
            "CONTACT_PHONE_NUMBER_LABEL" =>"Contact Phone Number",
            "COUNTRY_OD_RESIDENCE_LABEL" =>"Country of Residence*",
            "MUSIC_GENRE_LABEL" =>"Music Genre*",
            "SELECT" =>"Select...",
            "STATE_LABEL" =>"State*",
            "PASSWORD_LABEL" =>"Password*",
            "CONFIRM_PASSWORD_LABEL" =>"Confirm Password*",
            "SOCIAL_MEDIA_HANDLES" =>"Social Media Handles",
            "INSTAGRAM" =>"Instagram",
            "FACEBOOK" =>"Facebook",
            "TWITTER" =>"Twitter",
            "USERNAME" =>"@username",
            "AGREE_TO_FANCLUB" =>"By proceeding you agree to Fanclub's",
            "TERMS_AND_CONDITIONS" =>"Terms & Conditions",
            "AND" =>"and",
            "PRIVACY_POLICY" =>"Privacy Policy",
            "CONTINUE" =>"Continue",
            "HAVE_AN_ACCOUNT" =>"Have an Account?",
            "SIGN_IN" =>"Sign In",
        ],
        "Home" =>[
            "SEARCH_ARTIST_AND_SONGS" =>"Search Artists or Songs",
            "HOME" =>"Home",
            "SEARCH" =>"Search",
            "MY_COLLECTION" =>"My Collection",
            "ACCOUNT" =>"Account",
        ],
        "MyCollection" =>[
            "SEARCH_ARTIST_AND_SONGS" =>"Search Artists or Songs",
            "RECENTLY_PLAYED" =>"Recently Played",
        ],
        "CreatePlaylist" =>[
            "CREATE_PLAYLIST" =>"Create Playlist",
            "PLAYLIST_NAME" =>"Playlist Name*",
        ],
        "MySongs" =>[
            "MY_SONGS" =>"My Songs",
            "FAVOURITES" =>"Favourites",
            "DOWNLOADS" =>"Downloads",
            "PLAY_ALL" =>"Play All",
        ],
        "StartNewTopic" =>[
            "START_NEW_TOPIC" =>"Start New Topic",
            "START_NEW_TOPIC_IN_FORUM" =>"Start New Topic in Forum",
            "CREATE_NEW_TOPIC_DESC" =>"Create new topic to have amazing discussion",
            "TOPIC" =>"Topic*",
            "DESCRIPTION" =>"Description*",
            "SUBMIT" =>"Submit",
        ],
        "ContactUs" =>[
            "CONTACT_US" =>"Contact Us",
            "HAVE_QUERY" =>"Have a query? contact us here.",
            "LEAVE_FEEDBACK" =>"Want to leave feedback? We'd love to hear from you.",
            "YOUR_NAME" =>"Your Name*",
            "EMAIL_ADDRESS" =>"Email Address*",
            "WRITE_YOUR_MSG" =>"Write your message here",
            "SUBMIT" =>"Submit",
            "FOLLOW_US" =>"Follow Us",
        ],
        "UploadSong" =>[
            "UPLOAD_SONG" =>"Upload Song",
            "SELECT_FILE_TO_UPLOAD" =>"Select file to upload",
            "UPLOAD_DESC" =>"mp3, mp4 or mkv. Max 100MB",
            "THUMBNAIL" =>"Thumbnail",
            "SELECT_THUMBNAIL" =>"Set thumbnail for your song",
            "SELECT_THUMBNAIL_DESC" =>"jpg or jpeg . Max 2MB",
            "SONG_NAME" =>"Song Name*",
            "ARTIST" =>"Artist",
            "SELECT_GENRE" =>"Select Genre*",
            "ARTIST_TAGS" =>"Add Tags",
            "UPLOAD" =>"Upload",
        ],
        "AboutMe" =>[
            "ABOUT_ME" =>"About Me",
            "ABOUT_ME_LABEL" =>"About Me*",
            "SAVE_CHANGES" =>"Save Changes",
        ],
        "CreateNews" =>[
            "CREATE_NEWS" =>"Create News",
            "NEWS_TITLE" =>"News Title*",
            "DESCRIPTION" =>"Description*",
        ],
        "CreateEvent" =>[
            "CREATE_EVENT" =>"Create Event",
            "COVER_PHOTO" =>"Cover Photo",
            "SAVE_COVER_PHOTO" =>"Set cover photo for your event",
            "COVER_PHOTO_DESC" =>"jpg or jpeg . Max 2MB",
            "EVENT_TITLE" =>"Event Title*",
            "EVENT_DESC" =>"Event Description*",
            "LOCATION" =>"Location*",
            "SELECT_DATE" =>"Select Date *",
            "SELECT_TIME" =>"Select Time*",
        ],
        "EditProfileFan" =>[
            "EDIT_PROFILE" =>"Edit Profile",
            "YOUR_NAME" =>"Your Name*",
            "EMAIL_ADDRESS" =>"Email Address*",
            "COUNTRY_OF_RESIDENCE" =>"Country of Residence*",
            "STATE" =>"State*",
            "PHONE_NUMBER" =>"Phone Number",
            "DATE_OF_BIRTH" =>"Date of Birth*",
            "GENDER" =>"Gender*",
            "MALE" =>"Male",
            "FEMALE" =>"Female",
            "SAVE_CHANGES" =>"Save Changes",
        ],
        "EditProfileArtist" =>[
            "EDIT_PROFILE" =>"Edit Profile",
            "PROFILE_NAME" =>"Your Artist Profile Name*",
            "CONTACT_NAME" =>"Contact Name*",
            "CONTACT_EMAIL" =>"Contact Email*",
            "COUNTRY_OF_RESIDENCE" =>"Country of Residence*",
            "STATE" =>"State*",
            "CONTACT_PHONE" =>"Contact Phone",
            "PROFILE_TYPE" =>"Profile Type*",
            "BAND" =>"Band",
            "SOLO_MALE" =>"Solo Male",
            "SOLO_FEMALE" =>"Solo Female",
            "SAVE_CHANGES" =>"Save Changes",
        ],
        "General" =>[
            "TOP_ARTISTS" =>"Top Artists",
            "FAVOURITE_PLAYLISTS" =>"Favorite Playlists",
            "DOWNLOADS" =>"Downloads",
            "PLAY_ALL" =>"Play All",
            "SEARCH_ARTIST_AND_SONGS" =>"Search Artists or Songs",
            "RECENT_SEARCHES" =>"Recent Searches",
            "ABOUT_ARTIST" =>"About Artist",
            "NEWS" =>"News",
            "CREATE_NEWS" =>"Create News",
            "UPCOMING_EVENTS" =>"Upcoming Events",
            "MY_ACCOUNT" =>"My Account",
            "FREQUENTLY_ASKED_QUESTIONS" =>"Frequently Asked Questions",
            "TERMS_AND_CONDITIONS" =>"Terms & Conditions",
            "PRIVACY_POLICY" =>"Privacy Policy",
            "MY_SONGS" =>"My Songs",
            "SEARCH_SONGS" =>"Search Songs",
        ],
        "errorCodes" =>[
            "501" =>"Please fill all details",
            "502" =>"Please enter first name.",
            "503" =>"Please enter last name.",
            "504" =>"Please enter gender.",
            "505" =>"Please enter birthdate.",
            "506" =>"Please enter contact number.",
            "507" =>"Please enter Email-id.",
            "508" =>"Please enter proper first name.",
            "509" =>"Please enter proper last name.",
            "510" =>"Please enter valid contact number.",
            "511" =>"Password must contain at least 8 characters, including uppercase, lowercase, numbers and special characters.",
            "512" =>"Please enter old password.",
            "513" =>"Please enter new password.",
            "514" =>"Please enter confirm password.",
            "515" =>"your new password must be different from your previous password.",
            "516" =>"confirmation password does not match new password.",
            "517" =>"Please enter password.",
            "518" =>"Please enter send OTP.",
            "519" =>"Please enter valid Email-id.",
            "520" =>"Please enter message.",
            "521" =>"Please select report type.",
            "522" =>"Please enter street name/number.",
            "523" =>"Please select city.",
            "524" =>"Please select area.",
            "525" =>"Please select country code.",
            "526" =>"Please enter post code.",
            "527" =>"Please enter mobile number.",
            "528" =>"No internet connection found.",
            "529" =>"We are not able to connect to our server.",
            "530" =>"No data found.",
            "531" =>"We are currently under maintenance and will return shortly.",
            "532" =>"No message received.",
            "564" =>"LOGOUT",
            "565" =>"Are you sure,you wants to Logout from app. Please confirm.",
            "566" =>"Please select card value",
            "567" =>"Please enter your Name",
            "568" =>"Please enter Recipient Name",
            "569" =>"Sorry! no result found",
            "570" =>"Please modified you search criteria and will find result matching your needs.",
            "571" =>"Your recent search",
            "572" =>"Do you want to discard the changes?",
            "573" =>"You modified some filter.What would you like to do with these changes?",
            "574" =>"Please select card style",
            "575" =>"Please enter amount within range",
            "576" =>"Please enter amount",
            "577" =>"Code Copied.",
            "581" =>"Please fill all details",
            "582" =>"Please enter card name",
            "583" =>"Please enter card number",
            "584" =>"A credit card number must have between 13 and 16 digits.",
            "585" =>"Please select expiry month",
            "586" =>"Please select expiry year",
            "587" =>"Please enter CVV Number",
            "588" =>"Your product removed from wishlist",
            "1001" =>"Problem with Sending OTP",
            "1002" =>"Mobile No. Not Registered",
            "1003" =>"Invalid OTP",
            "1004" =>"Problem with SignUp",
            "1005" =>"Mobile No. Already Registered",
            "1006" =>"Problem with Login Type",
            "1007" =>"Problem with Login",
            "1008" =>"Invalid Password",
            "1009" =>"Please Enter Valid Password",
            "1010" =>"You are not authorize to Access",
            "1011" =>"Operation allowed only in HTTPS",
            "1012" =>"No Data Found!",
            "1013" =>"Wrong gift card name",
            "1014" =>"This Gift Code already exists",
            "1015" =>"Specified Gift Card for current user is not found.",
            "1016" =>"Cannot remove gift card.",
            "1017" =>"Problem with saving review.",
            "1018" =>"Old Password Is Wrong",
            "1019" =>"Your password and confirmation password do not match",
            "1020" =>"You are Not Register with us.",
            "1021" =>"The card could not be saved.",
            "1022" =>"Token is invalid.",
            "1024" =>"Please Try Again",
            "1031" =>"You are not registered with us",
            "1032" =>"Please enter mobile / email address.",
            "1037" =>"please login",
            "1042" =>"Something went wrong. Please try again",
            "1043" =>"The order could not be processed.",
        ],
    ];
      

    public static function getVariables(){
        return self::$array;
    }  
}
